### ISSUE TITLE
Thaumcraft 4.2 Warp Effects crashing players out for real

### ISSUE THREAD

**Issue by Fuhrmaaj** [BBoldt/Unabridged#207]
If I get 2-3 warp effects simultaneously, particulary Sunscorched and Unnatural Hunger, then the server boots the player over and over. The client doesn't crash out, so you can rejoin and will get ejected within 5s on average.

I heard that disabling warp effects may have a permanent impact on what can and can't be researched even if warp effects are re-enabled down the road. Anyways, I'm pretty much humped until the next update unless I do something about it. Any ideas?

Server Side
========
[20:19:23] [Server thread/INFO]: Kation joined the game
[20:19:30] [Server thread/WARN]: Failed to handle packet for /XXX.XX.XX.XX:59608
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(SourceFile:98) ~[jg.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_25]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:521) ~[sv.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293) ~[sv.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318) ~[sa.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1559) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
[20:19:30] [Server thread/INFO]: Kation lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[20:19:30] [Server thread/INFO]: Kation left the game

Client Side
========

[20:18:53] [Thread-43/INFO]: [CHAT] §e[#Unabridged] Fuhrmaaj joined the channel
[20:18:54] [Client thread/INFO]: [CHAT] Hello, Kation!
[20:18:54] [Client thread/INFO]: [CHAT] Server MOTD
[20:18:55] [Client thread/INFO]: [CHAT] Automagy v0.16 is now available. (You are running v0.14.)
[20:18:55] [Client thread/INFO]: [CHAT] §7§oCobble hogging your inventory? Want to send your precious
[20:18:55] [Client thread/INFO]: [CHAT] §7§ofinds back to base -- automatically? We've got just the thing!
[20:18:55] [Client thread/INFO]: [CHAT] Click [this link] for more info and downloads.
[20:18:57] [Client thread/INFO]: [CHAT] InvTweaks: Configuration loaded.
[20:18:57] [Client thread/WARN]: Could not find uniform named InSize in the specified shader program.
[20:18:57] [Client thread/WARN]: Could not find uniform named Time in the specified shader program.
[20:18:57] [Client thread/WARN]: Could not find uniform named ScreenSize in the specified shader program.
[20:19:21] [Client thread/INFO]: Connecting to XXX.XX.XX.XX, 25565
[20:19:25] [Client thread/INFO]: [CHAT] Hello, Kation!
[20:19:25] [Client thread/INFO]: [CHAT] Server MOTD
[20:29:21] [Client thread/INFO]: Connecting to XXX.XX.XX.XX, 25565
[20:29:25] [Client thread/INFO]: [CHAT] Hello, Kation!
[20:29:25] [Client thread/INFO]: [CHAT] Server MOTD

**Comment by BBoldt** [comment]
I have determined that potion IDs are all fucked up.

I shall fix them for the next release.
