### ISSUE TITLE
Voidwalker sash crashes client

### ISSUE THREAD

**Issue by Wenoc** [BBoldt/Unabridged#393]
Seems this is a known bug: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2437825-tainted-magic-1-1-5-4-a-thaumcraft-addon?page=27

<b>Server log:</b>

[23:04:35] [Server thread/WARN]: Failed to handle packet for <snip/>
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:349) ~[mw.class:?]
        at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) ~[ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
        at taintedmagic.common.items.ItemBaubleVoidSash.onWornTick(ItemBaubleVoidSash.java:112) ~[ItemBaubleVoidSash.class:?]
        at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:31) ~[EventHandlerEntity.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_56_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295) ~[mw.class:?]
        ... 12 more
[23:04:36] [Server thread/INFO]: <snip> lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[23:04:36] [Server thread/INFO]: <snip/> left the game

**Comment by billm** [comment]
Had the same issue on my server and found the same thread "end of August earliest" fix is a bit annoying.  The only positive is that it doesn't crash the server, only corrupts the users .baub file - an easy fix, rm that from the server and the player can log in again.  Is there any way to disable the infusion recipe for this item (there's no config for it)?

**Comment by BBoldt** [comment]
I'll disable the item for now with modtweaker.

**Comment by BBoldt** [comment]
temp fixed in r5

**Comment by Wenoc** [comment]
Thank you!
