### ISSUE TITLE
Twilight Portal not opening

### ISSUE THREAD

**Issue by bjornthv** [BBoldt/Unabridged#478]
![2016-01-03_21 00 58](https://cloud.githubusercontent.com/assets/5991989/12080514/fba1a63e-b25c-11e5-80f5-266a8d33e17f.png)

The setup is as is; 2x2 hole in dirt/grass blocks, surrounded by flowers, threw in diamond and..... nothing happened.... I reloaded/reinstalled to the latest version, 9a...

Restarted minecraft/server, to no avail... Running all the standard mods (Standard Config) + Optifine + Faithfull Resource Pack...

**Comment by bjornthv** [comment]
Flowers are Vanilla Dandelions, FYI.

**Comment by bjornthv** [comment]
Some additional info, as soon as I throw the Diamond in, Thaumcraft also stops working, and I get the following warnings/errors in the log:

[03/1/2016 21:18:04 PM] java.lang.ArrayIndexOutOfBoundsException: 3
[03/1/2016 21:18:04 PM] 	at thaumcraft.common.items.ItemLootBag.func_77617_a(ItemLootBag.java:44) ~[ItemLootBag.class:?]
[03/1/2016 21:18:04 PM] 	at makeo.gadomancy.common.items.ItemArcanePackage.func_77617_a(ItemArcanePackage.java:44) ~[ItemArcanePackage.class:?]
[03/1/2016 21:18:04 PM] 	at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.execute(ItemList.java:206) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
[03/1/2016 21:18:04 PM] [21:18:04] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting makeo.gadomancy.common.items.ItemArcanePackage@20793f2e:8 ItemArcanePackage
[03/1/2016 21:18:04 PM] java.lang.ArrayIndexOutOfBoundsException: 4
[03/1/2016 21:18:04 PM] 	at thaumcraft.common.items.ItemLootBag.func_77617_a(ItemLootBag.java:44) ~[ItemLootBag.class:?]
[03/1/2016 21:18:04 PM] 	at makeo.gadomancy.common.items.ItemArcanePackage.func_77617_a(ItemArcanePackage.java:44) ~[ItemArcanePackage.class:?]
[03/1/2016 21:18:04 PM] 	at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.execute(ItemList.java:206) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
[03/1/2016 21:18:04 PM] [21:18:04] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting makeo.gadomancy.common.items.ItemArcanePackage@20793f2e:10 ItemArcanePackage
[03/1/2016 21:18:04 PM] java.lang.ArrayIndexOutOfBoundsException: 5
[03/1/2016 21:18:04 PM] 	at thaumcraft.common.items.ItemLootBag.func_77617_a(ItemLootBag.java:44) ~[ItemLootBag.class:?]
[03/1/2016 21:18:04 PM] 	at makeo.gadomancy.common.items.ItemArcanePackage.func_77617_a(ItemArcanePackage.java:44) ~[ItemArcanePackage.class:?]
[03/1/2016 21:18:04 PM] 	at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.execute(ItemList.java:206) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
[03/1/2016 21:18:04 PM] [21:18:04] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting makeo.gadomancy.common.items.ItemArcanePackage@20793f2e:12 ItemArcanePackage
[03/1/2016 21:18:04 PM] java.lang.ArrayIndexOutOfBoundsException: 6
[03/1/2016 21:18:04 PM] 	at thaumcraft.common.items.ItemLootBag.func_77617_a(ItemLootBag.java:44) ~[ItemLootBag.class:?]
[03/1/2016 21:18:04 PM] 	at makeo.gadomancy.common.items.ItemArcanePackage.func_77617_a(ItemArcanePackage.java:44) ~[ItemArcanePackage.class:?]
[03/1/2016 21:18:04 PM] 	at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.execute(ItemList.java:206) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
[03/1/2016 21:18:04 PM] [21:18:04] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting makeo.gadomancy.common.items.ItemArcanePackage@20793f2e:14 ItemArcanePackage
[03/1/2016 21:18:04 PM] java.lang.ArrayIndexOutOfBoundsException: 7
[03/1/2016 21:18:04 PM] 	at thaumcraft.common.items.ItemLootBag.func_77617_a(ItemLootBag.java:44) ~[ItemLootBag.class:?]
[03/1/2016 21:18:04 PM] 	at makeo.gadomancy.common.items.ItemArcanePackage.func_77617_a(ItemArcanePackage.java:44) ~[ItemArcanePackage.class:?]
[03/1/2016 21:18:04 PM] 	at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.ItemList$1.execute(ItemList.java:206) [ItemList$1.class:?]
[03/1/2016 21:18:04 PM] 	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
[03/1/2016 21:18:07 PM] [OptiFine] Expand tessellator buffer, old: 524288, new: 1048576
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:13 PM] [21:18:13] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:22 PM] [21:18:22] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:18:32 PM] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft:liquid.swim
[03/1/2016 21:19:23 PM] [21:19:23] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:19:23 PM] [21:19:23] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:19:23 PM] [21:19:23] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item
[03/1/2016 21:19:23 PM] [21:19:23] [NEI Item Filtering/INFO] [Sanguimancy]: No mod found for this item

**Comment by BBoldt** [comment]
working for me

https://dl.dropboxusercontent.com/u/134976541/ShareX/2016-01/2016-01-12_16-37-36.mp4
