### ISSUE TITLE
Piston Crash

### ISSUE THREAD

**Issue by 0mbarr** [BBoldt/Unabridged#567]
**Minecraft version:**
1.10.2
**Unabridged or Abridged version:**
5.1
**Issue Description:**
Crash when picking up pistons
**Steps to Reproduce:**
Pick up or throw a piston on the ground
**Crash report or log (uploaded to gist.github.com or pastebin.com):**
// You're mean.

Time: 11/23/16 8:46 PM
Description: Ticking player

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} to null on block minecraft:piston, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:222)
	at net.minecraft.block.BlockPistonBase.func_176203_a(BlockPistonBase.java:424)
	at biomesoplenty.common.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_201_AchievementEventHandler_onItemPickup_ItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(FMLCommonHandler.java:580)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:410)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by adegarimore** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/903
Looks like it was a Biomes O' Plenty Bug. Thanks for the bug report. :)

Will be fixed in R6

**Comment by adegarimore** [comment]
I shouldn't close this until the update if out.

**Comment by adegarimore** [comment]
Fixed in Beta: 6
