### ISSUE TITLE
HTTPS BUG

### ISSUE THREAD

**Issue by maggi373** [BBoldt/Unabridged#649]
HTTPS module is crashing
Check any log

**Comment by maggi373** [comment]
http does not work either

**Comment by BBoldt** [comment]
post the log....

**Comment by maggi373** [comment]
just run the game and view your log

**Comment by maggi373** [comment]
this crash bug is also in 3.18.x and 3.19.x

**Comment by maggi373** [comment]
[2021-01-04-5.log](https://github.com/BBoldt/Unabridged/files/5833452/2021-01-04-5.log)

**Comment by BBoldt** [comment]
Are you referring to this?

https://gist.github.com/BBoldt/7321a7eec6420babedb891ae37d4a224

If so it's the fault of inpurecore, which got removed in 3.19.1 so I'm not sure why you have that file still. Which launcher are you using?

If that isn't what you're talking about please explain.

If you're going to post issues here please give me as much info as possible. I check issues when I have downtime at work sometimes, and I can't help if you don't explain the issue with any detail at all. There is a template for a reason.

**Comment by maggi373** [comment]
Just search http or https, almost all entries are crashes

**Comment by maggi373** [comment]
So more or less every mod using https cant use it like for capes or other functions, http too

**Comment by maggi373** [comment]
And this is an modpack specific thing, there is an mod doing this most likely

**Comment by BBoldt** [comment]
Most of them are update checkers in mods that aren't on the internet anymore... This one is steve's carts:

```
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: https://dl.dropbox.com/u/46486053/RemoteInfo.txt
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at vswe.stevescarts.Fancy.FancyPancyLoader.run(FancyPancyLoader.java:51)
[05:14:10] [Thread-8/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by BBoldt** [comment]
cofh:
```
[05:14:14] [CoFHUpdater:CoFHCore/ERROR]: Update check for CoFH Core failed.
java.io.FileNotFoundException: https://raw.githubusercontent.com/CoFH/VERSION/master/CoFHCore
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at java.net.URL.openStream(URL.java:1038) ~[?:1.8.0_51]
	at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:55) [UpdateCheckThread.class:?]
```

**Comment by BBoldt** [comment]
This one seems to be an actual error as it's Mekanism, and the urls do work but it's not connecting:
```
	Line 1648: [05:15:00] [Thread-18/ERROR]: An error occured while connecting to URL 'http://aidancbrady.com/data/versions/Mekanism.txt.'
	Line 1649: [05:15:00] [Thread-18/ERROR]: An error occured while connecting to URL 'http://aidancbrady.com/data/capes/Mekanism.txt.'
```

**Comment by BBoldt** [comment]
this one is AM2 and the url it's trying to connect to is gone again:
```
[05:15:43] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.UnknownHostException: arcanacraft.qorconcept.com
[05:15:43] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[05:15:43] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[05:15:43] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[05:15:43] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.Socket.connect(Socket.java:589)
[05:15:43] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.Socket.connect(Socket.java:538)
[05:15:43] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
```

**Comment by BBoldt** [comment]
more missing URLS:

```
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.twitch.tv/kraken/chat/emoticon_images?client_id=gdhi94otnk7c7746syjv7gkr6bizq4w&emotesets=19194
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1489)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eiramoticons.addon.TwitchEmotesAPI.newPrimeEmotesReader(TwitchEmotesAPI.java:61)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eiramoticons.addon.pack.TwitchPrimePack.<init>(TwitchPrimePack.java:34)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.blay09.mods.eiramoticons.ClientProxy$1.run(ClientProxy.java:114)
[05:15:59] [Emote Loader/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: https://raw.githubusercontent.com/Extegral/Forgotten-Relics/master/version.txt
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[05:15:59] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
```

**Comment by BBoldt** [comment]
Journeymap, this url exists but I think the format may have changed to something 1.7.10 journeymap doesn't recognize
```
[05:16:07] [JM-VersionCheck-1/ERROR]: Could not check version URL
java.io.IOException: Server returned HTTP response code: 403 for URL: http://widget.mcf.li/mc-mods/minecraft/journeymap-32274.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at java.net.URL.openStream(URL.java:1038) ~[?:1.8.0_51]
	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:131) [VersionCheck$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by BBoldt** [comment]
That looks like all of them, so the only one that's actually not working seems to be mekanism. All the others are due to URLs that point to nothing. It's a pack filled with old mods, there are a lot of things they check for that no longer exist or no longer exist in the same form.

There is nothing blocking mods from connecting to the internet, here are examples of mods doing so:

```
[05:14:41] [Client thread/INFO]: Version check success: appliedenergistics2 required / rv3-beta-6 detected
[05:14:41] [Client thread/INFO]: Version check success: Botany required / 2.0.22.7 detected
[05:14:41] [Client thread/INFO]: Version check success: Forestry@[4.0.8.36,) required / 4.2.16.64 detected
```

Armourer's Workshop having no issues checking for updates:

```
[05:14:21] [Armourer's Workshop update thread./INFO]: Starting Update Check
[05:14:21] [Client thread/INFO]: Registering skin: armourers:head
[05:14:21] [Client thread/INFO]: Registering skin: armourers:chest
[05:14:21] [Client thread/INFO]: Registering skin: armourers:legs
[05:14:21] [Client thread/INFO]: Registering skin: armourers:feet
[05:14:21] [Client thread/INFO]: Registering skin: armourers:wings
[05:14:21] [Client thread/INFO]: Registering skin: armourers:sword
[05:14:21] [Client thread/INFO]: Registering skin: armourers:shield
[05:14:21] [Client thread/INFO]: Registering skin: armourers:bow
[05:14:21] [Client thread/INFO]: Registering skin: armourers:pickaxe
[05:14:21] [Client thread/INFO]: Registering skin: armourers:axe
[05:14:21] [Client thread/INFO]: Registering skin: armourers:shovel
[05:14:21] [Client thread/INFO]: Registering skin: armourers:hoe
[05:14:21] [Client thread/INFO]: Registering skin: armourers:item
[05:14:21] [Client thread/INFO]: Registering skin: armourers:block
[05:14:21] [Client thread/INFO]: Registering skin: armourers:outfit
[05:14:21] [Client thread/INFO]: Registering equipment cube - id:0 name:Cube
[05:14:21] [Client thread/INFO]: Registering equipment cube - id:1 name:CubeGlowing
[05:14:21] [Client thread/INFO]: Registering equipment cube - id:2 name:CubeGlass
[05:14:21] [Client thread/INFO]: Registering equipment cube - id:3 name:CubeGlassGlowing
[05:14:21] [Client thread/INFO]: BuildCraft robot skin support active.
[05:14:21] [Client thread/INFO]: Skin render type set to: model_attachment
[05:14:21] [Client thread/INFO]: Buildcraft detected! - Enabling knishes support.
[05:14:21] [Client thread/INFO]: Thermal Foundation: Loading Plugins...
[05:14:21] [Client thread/INFO]: Thermal Foundation: Finished Loading Plugins.
[05:14:21] [Armourer's Workshop update thread./INFO]: Latest version for Minecraft 1.7.10 is 0.48.5.
[05:14:21] [Armourer's Workshop update thread./INFO]: Mod is up to date with the latest version.
```

**Comment by BBoldt** [comment]
So, unless you can prove otherwise or have any idea of what is going on, HTTPS isn't "crashing". I don't know what's keeping capes from loading in Mekanism.

**Comment by BBoldt** [comment]
related?? https://github.com/mekanism/Mekanism/issues/5457

**Comment by maggi373** [comment]
what im trying to say that some of the errors are not normal, some of these mods are actually connecting in other packs and something is stopping them. This config aint the one you should be looking in. but that inpure fault is the same im getting with mekanism the newer one, and other mods that use internet for stuff. So optifine capes wont work for those that have that. is this an update disabler mod of some sort? And this is an crash since the module wont work. So mods using internet wont work and it should work, its "saving" your pack because its throwing excemptions and should not go without fixing it. Can be related to issues with uplink?

**Comment by maggi373** [comment]
but yes, im sad that my capes dont work

**Comment by BBoldt** [comment]
So, it turns out this isn't my fault at all, or exclusive to this pack as you've said.

Here is a log of *just mekanism, multipart, and forge 1614*
https://slexy.org/raw/s20gWT4TGv?token=73c59ed57742eb996deb3a5adbadfd98dc9831f51102e262cb2fa58a3cc0741a&ts=1611139616

and look at that:
```[14:48:31] [Client thread/ERROR]: Unable to establish a connection to the server, technic-solder.eu-central-1.linodeobjects.com
[14:48:31] [Client thread/INFO]: Version 9.10.6 initializing...
[14:48:32] [Thread-13/ERROR]: An error occured while connecting to URL 'https://technic-solder.eu-central-1.linodeobjects.com/mekanism/Mekanism.txt.'
[14:48:32] [Thread-13/ERROR]: An error occured while connecting to URL 'http://aidancbrady.com/data/capes/Mekanism.txt.'

**Comment by BBoldt** [comment]
Also, next time you post an issue that is extremely vague and unexplained, I'm just going to close it immediately.

**Comment by maggi373** [comment]
Well i didnt want to ruin the suprise, it was an cape in my mod and it didnt work because ssl in your pack crashes. Anyway, ssl crashes in everything now (around month of may), i think an update for java borked it.
